package com.aidiaoemami.tahsinquran;

import android.content.Context;
import android.database.Cursor;
import android.database.SQLException;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;

import java.util.ArrayList;
import java.util.List;

import static android.content.ContentValues.TAG;

public class DataHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME = "tahsinquran.db";
//    private static final String DATABASE_TABLE = "quran";
    private static final int DATABASE_VERSION = 1;
    public DataHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
        // TODO Auto-generated constructor stub
    }
    @Override
    public void onCreate(SQLiteDatabase db) {
        String sql = "create table hukum(id integer primary key autoincrement, hukum string, cara_baca string);";
        String sql2 = "create table tahsin(id integer primary key autoincrement, lafadz text, transkripsi text);";
        String sql3 = "create table tajwid (id integer primary key autoincrement, huruf string, pola string, hukum integer, foreign key (hukum) references hukum(id));";
        //Log.d("Data", "onCreate: " + sql);
        db.execSQL(sql);
        db.execSQL(sql2);
        db.execSQL(sql3);

        DataModel a = new DataModel(db);
        a.insert_hukum("Izhar", "Cara membacanya jelas dan terang tidak diperbolehkan untuk mendengung. Hukumnya dibaca Izhar apabila nun mati atau tanwin bertemu dengan salah satu huruf diantara 6 huruf berikut:");
        a.insert_hukum("Iqlab", "Bacaan nun mati atau tanwin berubah menjadi bunyi mim. Hukum nya dibaca Iqlab apabila nun mati atau tanwin bertemu dengan huruf");
        a.insert_hukum("Idgham Bighunnah", "Memasukkan huruf satu ke dalam huruf berikutnya dan dibaca dengan dengung. Hukumnya dibaca Idgham Bighunnah apabila nun mati atau tanwin bertemu dengan salah satu huruf diantara 4 huruf berikut:");
        a.insert_hukum("Idgham Bilaghunnah", "Memasukkan huruf satu ke dalam huruf berikutnya dan dibaca tanpa dengung. Hukumnya dibaca Idgham Bilaghunnah apabila nun mati atau tanwin bertemu dengan salah satu huruf diantara 2 huruf berikut:");
        a.insert_hukum("Ikhfa", "Cara membacanya samar-samar (antara izhar dan idgham). Hukumnya dibaca Ikhfa apabila nun mati atau tanwin bertemu dengan salah satu huruf diantara 15 huruf berikut:");

        a.insert_tahsin("وَمَنْ أَحْسَنُ", "wamanahsanuُ");
        a.insert_tahsin("عَنْهُ", "anhu");
        a.insert_tahsin("وَمَنْ عَادَ","wamanada");
        a.insert_tahsin("عَلِيمًا حَكِيمًا","alimanhakiman");
        a.insert_tahsin("حَاسcٍ اِذَا","hasidinidza");
        a.insert_tahsin("مِنْهَا","minha");
        a.insert_tahsin("مِنْهُمْ","minhum");
        a.insert_tahsin("مِنْ أَهْلِ","minahli");
        a.insert_tahsin( "فَضْلٍ عَلَى","fadlinala");
        a.insert_tahsin("مِنْ حَيْثُ","minhaitsu");
        a.insert_tahsin("مِنْ خَيْرٍ","minkhoirin");
        a.insert_tahsin("عَذَابٌ أَلِيمٌ","adzaabunalimun");
        a.insert_tahsin("وَاسِعٌ عَلِيمٌ","wasiunalimun");
        a.insert_tahsin("مُحَرَّمٌ عَلَيْكُمْ","muharommunalaykum");
        a.insert_tahsin("أَجْرٌ غَيْرُ","ajrunghairu");
        a.insert_tahsin("مَنْ يَفْعَلُ","myyafalu");
        a.insert_tahsin("عَنْ نَفْسٍ","annafsin");
        a.insert_tahsin("مِنْ نَّارٍ","minnarin");
        a.insert_tahsin("لَهَبٍ وَّتَب","lahabiwwatab");
        a.insert_tahsin("رَسُولٌ مِنْهُمْ","rosulumminhum");
        a.insert_tahsin("إِلَٰهٌ وَاحِدْ","ilahuwahid");
        a.insert_tahsin("رِزْقًا لَكُمْ","rizkolakum");
        a.insert_tahsin("مُصَدِّقًا لِمَا","musoddiqollima");
        a.insert_tahsin( "وَمَنْ لَمْ","wamalam");
        a.insert_tahsin("فَإِنْ لَمْ","faillam");
        a.insert_tahsin("مِنْ لَ","milla");
        a.insert_tahsin( "مِّنْ رَّبِّكُمْ","mirrobbikum");
        a.insert_tahsin("مِّنْ رَّبِّهِمْ","mirrobbihim");
        a.insert_tahsin("يَكُنْ لَّهٗ","yakullahu");
        a.insert_tahsin("اَنْفُسَكُمْ","angfusakum");
        a.insert_tahsin("غَفُورٌ رَحِيم","ghofururrohim");
        a.insert_tahsin("اَنْبَتَكُمْ","ambatakum");
        a.insert_tahsin("اَبَدًا بِۢمَا","abadambima");
        a.insert_tahsin("مِّنْۢ بَيْنِ","mimbaini");
        a.insert_tahsin("مِنْ بَعْدِ","mimbadi");
        a.insert_tahsin("رَسُولٌ بِمَا","rosulumbima");
        a.insert_tahsin("صُمٌّ بُكْمٌ","summumbukmun");
        a.insert_tahsin("لَنْ تَمَسَّنَا","langtamasana");
        a.insert_tahsin("وَلَنْ تَفْعَلُوْا","walangtafalu");
        a.insert_tahsin("وَلَنْ تَرْضَىٰ","walangtardho");
        a.insert_tahsin("مَنْ كَسَبَ","mangkasaba");
        a.insert_tahsin("مَنْ كَانَ","mangkana");
        a.insert_tahsin("مِنْ فَضْلِ","mingfadli");
        a.insert_tahsin("وَمِنْ ذُرِّيَّتِ","wamingdzuriyyati");
        a.insert_tahsin("مِنْ تَحْتِهَا","mingtahtiha");
        a.insert_tahsin("اِنْ كُنْتُمْ","ingkungtum");
        a.insert_tahsin("عِنْدَ","ingda");
        a.insert_tahsin("مِنْ قَبْلِكُمْ","mingqoblikum");
        a.insert_tahsin("مِنْ سَيِّئَاتِكُمْ","mingsayyiatikum");
        a.insert_tahsin("مِنْ طَيِّبَاتِ","mingtoyyibati");
        a.insert_tahsin("مِنْ دِيَارِهِمْ","mingdiarihim");
        a.insert_tahsin("مِنْ صَدَقَةٍ","mingshodaqotin");
        a.insert_tahsin("كُنْ فَيَكُون","kungfayakun");
        a.insert_tahsin("يُنْظَرُون","yungzorun");

        a.insert_tajwid("ا","نْ ا", 1);
//        a.insert_tajwid("ا","ن ا", "نا",1);
//        a.insert_tajwid("ا","ن ا", "نا",1);
        a.insert_tajwid("ا","ًا ا" ,1);
        a.insert_tajwid("ا","ٍ ا", 1);
        a.insert_tajwid("ا","ٌ ا", 1);
        a.insert_tajwid("ع","نْ ع", 1);
        a.insert_tajwid("ع","نْع", 1);
//        a.insert_tajwid("ع","ن ع", "ina",1);
//        a.insert_tajwid("ع","نع", "ina",1);
        a.insert_tajwid("ع","ًا ع", 1);
        a.insert_tajwid("ع","ٍ ع", 1);
        a.insert_tajwid("ع","ٌ ع",1);
//        a.insert_tajwid("ا","una", "una",1);
//        a.insert_tajwid("ا","ani", "ani",1);
//        a.insert_tajwid("ا","ini", "ini",1);
//        a.insert_tajwid("ا","uni", "uni",1);
//        a.insert_tajwid("ا","anu", "anu",1);
//        a.insert_tajwid("ا","inu", "inu",1);
//        a.insert_tajwid("ا","unu", "unu",1);
        a.insert_tajwid("ه","نْ ه",1);
        a.insert_tajwid("ه","نْه",1);
//        a.insert_tajwid("ه","ن ه", "anha",1);
        a.insert_tajwid("ه","ًا ه",1);
        a.insert_tajwid("ه","ٍ ه",1);
        a.insert_tajwid("ه","ٌ ه",1);
//        a.insert_tajwid("ه","نه", "anha",1);

        a.insert_tajwid("ح","نْ ح",1);
        a.insert_tajwid("ح","نْح",1);
//        a.insert_tajwid("ح","ن ح", "inha",1);
//        a.insert_tajwid("ح","نح", "inha",1);
        a.insert_tajwid("ح","ًا ح",1);
        a.insert_tajwid("ح","ٍ ح", 1);
        a.insert_tajwid("ح","ٌ ح",1);
//        a.insert_tajwid("ح","unha", "unha",1);
//        a.insert_tajwid("ح","anhi", "anhi",1);
//        a.insert_tajwid("ح","inhi", "inhi",1);
//        a.insert_tajwid("ح","unhi", "unhi",1);
//        a.insert_tajwid("ح","anhu", "anhu",1);
//        a.insert_tajwid("ح","inhu", "inhu",1);
//        a.insert_tajwid("ح","unhu", "unhu",1);
        a.insert_tajwid("خ","نْ خ",1);
        a.insert_tajwid("خ","نْخ",1);
//        a.insert_tajwid("خ","ن خ", "ankh",1);
//        a.insert_tajwid("خ","نخ", "ankh",1);
        a.insert_tajwid("خ","ًا خ",1);
        a.insert_tajwid("خ","ٍ خ",1);
        a.insert_tajwid("خ","ٌ خ", 1);
//        a.insert_tajwid("خ","inkh", "inkh",1);
//        a.insert_tajwid("خ","unkh", "unkh",1);
        a.insert_tajwid("غ","نْ غ", 1);
        a.insert_tajwid("غ","نْغ", 1);
//        a.insert_tajwid("غ","ن غ", "angh",1);
//        a.insert_tajwid("غ","نغ", "angh",1);
        a.insert_tajwid("غ","ًا غ", 1);
        a.insert_tajwid("غ","ٍ غ", 1);
        a.insert_tajwid("غ","ٌ غ", 1);
//        a.insert_tajwid("غ","ingh", "ingh",1);
//        a.insert_tajwid("غ","ungh", "ungh",1);
        a.insert_tajwid("ب","نْ ب",2);
        a.insert_tajwid("ب","نْب", 2);
//        a.insert_tajwid("ب","ن ب", "amba",2);
//        a.insert_tajwid("ب","نب", "amba",2);
        a.insert_tajwid("ب","ًا ب", 2);
        a.insert_tajwid("ب","ٍ ب", 2);
        a.insert_tajwid("ب","ٌ ب", 2);
//        a.insert_tajwid("ب","inba", "imba",2);
//        a.insert_tajwid("ب","unba", "unba",2);
//        a.insert_tajwid("ب","anbi", "ambi",2);
//        a.insert_tajwid("ب","inbi", "imbi",2);
//        a.insert_tajwid("ب","unbi", "unbi",2);
//        a.insert_tajwid("ب","anbu", "ambu",2);
//        a.insert_tajwid("ب","inbu", "imbu",2);
//        a.insert_tajwid("ب","unbu", "unbu",2);
        a.insert_tajwid("ي","نْ ي", 3);
//        a.insert_tajwid("ي","ن ي", "ayya",3);
        a.insert_tajwid("ي","ًا ي", 3);
        a.insert_tajwid("ي","ٍ ي", 3);
        a.insert_tajwid("ي","ٌ ي", 3);
        a.insert_tajwid("ي dalam satu kalimat, sehingga tidak boleh dibaca Idgham","نْي", 1);
//        a.insert_tajwid("ي","inya", "iyya",3);
//        a.insert_tajwid("ي","unya", "uyya",3);
//        a.insert_tajwid("ي","anyu", "ayyu",3);
//        a.insert_tajwid("ي","inyu", "iyyu",3);
//        a.insert_tajwid("ي","unyu", "uyyu",3);
//        a.insert_tajwid("ي","anyi", "ayyi",3);
//        a.insert_tajwid("ي","inyi", "iyyi",3);
//        a.insert_tajwid("ي","unyi", "uyyi",3);
        a.insert_tajwid("ن","نْ ن", 3);
//        a.insert_tajwid("ن","ن ن", "anna",3);
        a.insert_tajwid("ن","ًا ن", 3);
        a.insert_tajwid("ن","ٍ ن", 3);
        a.insert_tajwid("ن","ٌ ن", 3);
        a.insert_tajwid("ن dalam satu kalimat, sehingga tidak boleh dibaca Idgham","نْن", 1);
//        a.insert_tajwid("ن","inna", "inna",3);
//        a.insert_tajwid("ن","unna", "unna",3);
//        a.insert_tajwid("ن","annu", "annu",3);
//        a.insert_tajwid("ن","innu", "innu",3);
//        a.insert_tajwid("ن","unnu", "unnu",3);
//        a.insert_tajwid("ن","anni", "anni",3);
//        a.insert_tajwid("ن","inni", "inni",3);
//        a.insert_tajwid("ن","unni", "unni",3);
//        a.insert_tajwid("م","anma", "amma",3);
//        a.insert_tajwid("م","inma", "imma",3);
        a.insert_tajwid("م","نْ م", 3);
//        a.insert_tajwid("م","ن م", "umma",3);
        a.insert_tajwid("م","ًا م", 3);
        a.insert_tajwid("م","ٍ م", 3);
        a.insert_tajwid("م","ٌ م", 3);
        a.insert_tajwid("م dalam satu kalimat, sehingga tidak boleh dibaca Idgham","نْم", 1);
//        a.insert_tajwid("م","anmi", "ammi",3);
//        a.insert_tajwid("م","inmi", "immi",3);
//        a.insert_tajwid("م","unmi", "ummi",3);
//        a.insert_tajwid("م","anmu", "ammu",3);
//        a.insert_tajwid("م","inmu", "immu",3);
//        a.insert_tajwid("م","unmu", "ummu",3);
        a.insert_tajwid("و","نْ و", 3);
//        a.insert_tajwid("و","ن و", "awwa",3);
        a.insert_tajwid("و","ًا و", 3);
        a.insert_tajwid("و","ٍ و", 3);
        a.insert_tajwid("و","ٌ و", 3);
        a.insert_tajwid( "و dalam satu kalimat, sehingga tidak boleh dibaca Idgham","نْو", 1);
//        a.insert_tajwid("و","inwa", "iwwa",3);
//        a.insert_tajwid("و","unwa", "uwwa",3);
//        a.insert_tajwid("و","anwi", "awwi",3);
//        a.insert_tajwid("و","inwi", "iwwi",3);
//        a.insert_tajwid("و","unwi", "uwwi",3);
//        a.insert_tajwid("و","anwu", "awwu",3);
//        a.insert_tajwid("و","inwu", "iwwu",3);
//        a.insert_tajwid("و","unwu", "uwwu",3);
        a.insert_tajwid("ل","نْ ل",4);
        a.insert_tajwid("ل","نْل",4);
//        a.insert_tajwid("ل","ن ل","alla",4);
//        a.insert_tajwid("ل","نل","alla",4);
        a.insert_tajwid("ل","ًا ل", 4);
        a.insert_tajwid("ل","ٍ ل", 4);
        a.insert_tajwid("ل","ٌ ل", 4);
//        a.insert_tajwid("ل","inla","illa",4);
//        a.insert_tajwid("ل","unla","ulla",4);
//        a.insert_tajwid("ل","anlu","allu",4);
//        a.insert_tajwid("ل","inlu","illu",4);
//        a.insert_tajwid("ل","unlu","ullu",4);
//        a.insert_tajwid("ل","anli","alli",4);
//        a.insert_tajwid("ل","inli","illi",4);
//        a.insert_tajwid("ل","unli","ulli",4);
        a.insert_tajwid("ر","نْ ر",4);
        a.insert_tajwid("ر","نْر",4);
//        a.insert_tajwid("ر","ن ر","arra",4);
//        a.insert_tajwid("ر","نر","arra",4);
        a.insert_tajwid("ر","ًا ر", 4);
        a.insert_tajwid("ر","ٍ ر", 4);
        a.insert_tajwid("ر","ٌ ر", 4);
//        a.insert_tajwid("ر","inra","irra",4);
//        a.insert_tajwid("ر","unra","urra",4);
//        a.insert_tajwid("ر","anri","arri",4);
//        a.insert_tajwid("ر","inri","irri",4);
//        a.insert_tajwid("ر","unri","urri",4);
//        a.insert_tajwid("ر","anru","arru",4);
//        a.insert_tajwid("ر","inru","irru",4);
//        a.insert_tajwid("ر","unru","urru",4);
        a.insert_tajwid("ص","نْ ص",5);
        a.insert_tajwid("ص","نْص",5);
//        a.insert_tajwid("ص","ن ص","angsho",5);
//        a.insert_tajwid("ص","نص","angsho",5);
        a.insert_tajwid("ص","ًا ص", 5);
        a.insert_tajwid("ص","ٍ ص", 5);
        a.insert_tajwid("ص","ٌ ص", 5);
//        a.insert_tajwid("ص","insho","ingsho",5);
//        a.insert_tajwid("ص","unsho","ungsho",5);
        a.insert_tajwid("ف","نْ ف",5);
        a.insert_tajwid("ف","نْف",5);
//        a.insert_tajwid("ف","ن ف","angfa",5);
//        a.insert_tajwid("ف","نف","angfa",5);
        a.insert_tajwid("ف","ًا ف", 5);
        a.insert_tajwid("ف","ٍ ف", 5);
        a.insert_tajwid("ف","ٌ ف", 5);
//        a.insert_tajwid("ف","infa","ingfa",5);
//        a.insert_tajwid("ف","unfa","ungfa",5);
//        a.insert_tajwid("ف","anfi","angfi",5);
//        a.insert_tajwid("ف","infi","ingfi",5);
//        a.insert_tajwid("ف","unfi","ungfi",5);
//        a.insert_tajwid("ف","anfu","angfu",5);
//        a.insert_tajwid("ف","infu","ingfu",5);
//        a.insert_tajwid("ف","unfu","ungfu",5);
        a.insert_tajwid("ذ","نْ ذ",5);
        a.insert_tajwid("ذ","نْذ",5);
//        a.insert_tajwid("ذ","ن ذ","angdz",5);
//        a.insert_tajwid("ذ","نذ","angdz",5);
        a.insert_tajwid("ذ","ًا ذ", 5);
        a.insert_tajwid("ذ","ٍ ذ",5);
        a.insert_tajwid("ذ","ٌ ذ", 5);
//        a.insert_tajwid("ذ","indz","ingdz",5);
//        a.insert_tajwid("ذ","undz","ungdz",5);
        a.insert_tajwid("ث","نْ ث",5);
        a.insert_tajwid("ث","نْث",5);
//        a.insert_tajwid("ث","ن ث","angtsa",5);
//        a.insert_tajwid("ث","نث","angtsa",5);
        a.insert_tajwid("ث","ًا ث", 5);
        a.insert_tajwid("ث","ٍ ث", 5);
        a.insert_tajwid("ث","ٌ ث", 5);
//        a.insert_tajwid("ث","intsa","ingtsa",5);
//        a.insert_tajwid("ث","untsa","ungtsa",5);
//        a.insert_tajwid("ث","antsu","angtsu",5);
//        a.insert_tajwid("ث","intsu","ingtsu",5);
//        a.insert_tajwid("ث","untsu","ungtsu",5);
//        a.insert_tajwid("ث","antsi","angtsi",5);
//        a.insert_tajwid("ث","intsi","ingtsi",5);
//        a.insert_tajwid("ث","untsi","ungtsi",5);
        a.insert_tajwid("ت","نْ ت",5);
        a.insert_tajwid("ت","نْت",5);
//        a.insert_tajwid("ت","ن ت","angta",5);
//        a.insert_tajwid("ت","نت","angta",5);
        a.insert_tajwid("ت","ًا ت", 5);
        a.insert_tajwid("ت","ٍ ت", 5);
        a.insert_tajwid("ت","ٌ ت", 5);
//        a.insert_tajwid("ت","inta","ingta",5);
//        a.insert_tajwid("ت","unta","ungta",5);
//        a.insert_tajwid("ت","anti","angti",5);
//        a.insert_tajwid("ت","inti","ingti",5);
//        a.insert_tajwid("ت","unti","ungti",5);
//        a.insert_tajwid("ت","antu","angtu",5);
//        a.insert_tajwid("ت","intu","ingtu",5);
//        a.insert_tajwid("ت","untu","ungtu",5);
        a.insert_tajwid("ك","نْ ك",5);
        a.insert_tajwid("ك","نْك",5);
//        a.insert_tajwid("ك","ن ك","angka",5);
//        a.insert_tajwid("ك","نك","angka",5);
        a.insert_tajwid("ك","ًا ك", 5);
        a.insert_tajwid("ك","ٍ ك", 5);
        a.insert_tajwid("ك","ٌ ك", 5);
//        a.insert_tajwid("ك","inka","ingka",5);
//        a.insert_tajwid("ك","unka","ungka",5);
//        a.insert_tajwid("ك","anki","angk",5);
//        a.insert_tajwid("ك","inki","ingki",5);
//        a.insert_tajwid("ك","unki","ungki",5);
//        a.insert_tajwid("ك","anku","angku",5);
//        a.insert_tajwid("ك","inku","ingku",5);
//        a.insert_tajwid("ك","unku","ungku",5);
        a.insert_tajwid("ج","نْ ج",5);
        a.insert_tajwid("ج","نْج",5);
//        a.insert_tajwid("ج","ن ج","angja",5);
//        a.insert_tajwid("ج","نج","angja",5);
        a.insert_tajwid("ج","ًا ج", 5);
        a.insert_tajwid("ج","ٍ ج", 5);
        a.insert_tajwid("ج","ٌ ج", 5);
//        a.insert_tajwid("ج","inja","ingja",5);
//        a.insert_tajwid("ج","unja","ungja",5);
//        a.insert_tajwid("ج","anji","angji",5);
//        a.insert_tajwid("ج","inji","ingji",5);
//        a.insert_tajwid("ج","unji","ungji",5);
//        a.insert_tajwid("ج","anju","angju",5);
//        a.insert_tajwid("ج","inju","ingju",5);
//        a.insert_tajwid("ج","unju","ungju",5);
        a.insert_tajwid("د","نْ د",5);
        a.insert_tajwid("د","نْد",5);
//        a.insert_tajwid("د","ن د","angda",5);
//        a.insert_tajwid("د","ند","angda",5);
        a.insert_tajwid("د","ًا د",5);
        a.insert_tajwid("د","ٍ د", 5);
        a.insert_tajwid("د","ٌ د", 5);
//        a.insert_tajwid("د","inda","ingda",5);
//        a.insert_tajwid("د","unda","ungda",5);
//        a.insert_tajwid("د","andi","angdi",5);
//        a.insert_tajwid("د","indi","ingdi",5);
//        a.insert_tajwid("د","undi","ungdi",5);
//        a.insert_tajwid("د","andu","angdu",5);
//        a.insert_tajwid("د","indu","ingdu",5);
//        a.insert_tajwid("د","undu","ungdu",5);
        a.insert_tajwid("ش","نْ ش",5);
        a.insert_tajwid("ش","نْش",5);
//        a.insert_tajwid("ش","ن ش","angsy",5);
//        a.insert_tajwid("ش","نش","angsy",5);
        a.insert_tajwid("ش","ًا ش", 5);
        a.insert_tajwid("ش","ٍ ش", 5);
        a.insert_tajwid("ش","ٌ ش", 5);
//        a.insert_tajwid("ش","insy","ingsy",5);
//        a.insert_tajwid("ش","unsy","ungsy",5);
        a.insert_tajwid("ق","نْ ق",5);
        a.insert_tajwid("ق","نْق",5);
//        a.insert_tajwid("ق","ن ق","angqo",5);
//        a.insert_tajwid("ق","نق","angqo",5);
        a.insert_tajwid("ق","ًا ق", 5);
        a.insert_tajwid("ق","ٍ ق", 5);
        a.insert_tajwid("ق","ٌ ق", 5);
//        a.insert_tajwid("ق","inqo","ingqo",5);
//        a.insert_tajwid("ق","unqo","ungqo",5);
//        a.insert_tajwid("ق","anqi","angqi",5);
//        a.insert_tajwid("ق","inqi","ingqi",5);
//        a.insert_tajwid("ق","unqi","ungqi",5);
//        a.insert_tajwid("ق","anqu","angqu",5);
//        a.insert_tajwid("ق","inqu","ingqu",5);
//        a.insert_tajwid("ق","unqu","ungqu",5);
        a.insert_tajwid("س","نْ س",5);
        a.insert_tajwid("س","نْس",5);
//        a.insert_tajwid("س","ن س","angsa",5);
//        a.insert_tajwid("س","نس","angsa",5);
        a.insert_tajwid("س","ًا س", 5);
        a.insert_tajwid("س","ٍ س", 5);
        a.insert_tajwid("س","ٌ س", 5);
//        a.insert_tajwid("س","insa","ingsa",5);
//        a.insert_tajwid("س","unsa","ungsa",5);
//        a.insert_tajwid("س","ansi","angsi",5);
//        a.insert_tajwid("س","insi","ingsi",5);
//        a.insert_tajwid("س","unsi","ungsi",5);
//        a.insert_tajwid("س","ansu","angsu",5);
//        a.insert_tajwid("س","insu","ingsu",5);
//        a.insert_tajwid("س","unsu","ungsu",5);
        a.insert_tajwid("ط","نْ ط",5);
        a.insert_tajwid("ط","نْط",5);
//        a.insert_tajwid("ط","ن ط","angto",5);
//        a.insert_tajwid("ط","نط","angto",5);
        a.insert_tajwid("ط","ًا ط", 5);
        a.insert_tajwid("ط","ٍ ط", 5);
        a.insert_tajwid("ط","ٌ ط", 5);
//        a.insert_tajwid("ط","into","ingto",5);
//        a.insert_tajwid("ط","unto","ungto",5);
//        a.insert_tajwid("ط","anti","angti",5);
//        a.insert_tajwid("ط","inti","ingti",5);
//        a.insert_tajwid("ط","unti","ungti",5);
//        a.insert_tajwid("ط","antu","angtu",5);
//        a.insert_tajwid("ط","intu","ingtu",5);
//        a.insert_tajwid("ط","untu","ungtu",5);
        a.insert_tajwid("ز","نْ ز",5);
        a.insert_tajwid("ز","نْز",5);
//        a.insert_tajwid("ز","ن ز","angza",5);
//        a.insert_tajwid("ز","نز","angza",5);
        a.insert_tajwid("ز","ًا ز", 5);
        a.insert_tajwid("ز","ٍ ز", 5);
        a.insert_tajwid("ز","ٌ ز", 5);
//        a.insert_tajwid("ز","inza","ingza",5);
//        a.insert_tajwid("ز","unza","ungza",5);
//        a.insert_tajwid("ز","anzi","angzi",5);
//        a.insert_tajwid("ز","inzi","ingzi",5);
//        a.insert_tajwid("ز","unzi","ungzi",5);
//        a.insert_tajwid("ز","anzu","angzu",5);
//        a.insert_tajwid("ز","inzu","ingzu",5);
//        a.insert_tajwid("ز","unzu","ungzu",5);
        a.insert_tajwid("ض", "نْ ض",5);
        a.insert_tajwid("ض", "نْض",5);
//        a.insert_tajwid("ض", "ن ض","angdo",5);
//        a.insert_tajwid("ض", "نض","angdo",5);
        a.insert_tajwid("ض","ًا ض", 5);
        a.insert_tajwid("ض","ٍ ض", 5);
        a.insert_tajwid("ض","ٌ ض", 5);
//        a.insert_tajwid("ض","indo","ingdo",5);
//        a.insert_tajwid("ض","undo","ungdo",5);
        a.insert_tajwid("ظ","نْ ظ",5);
        a.insert_tajwid("ظ","نْظ",5);
//        a.insert_tajwid("ظ","ن ظ","angzo",5);
//        a.insert_tajwid("ظ","نظ","angzo",5);
        a.insert_tajwid("ظ","ًا ظ", 5);
        a.insert_tajwid("ظ","ٍ ظ", 5);
        a.insert_tajwid("ظ","ٌ ظ", 5);
//        a.insert_tajwid("ظ","inzo","ingzo",5);
//        a.insert_tajwid("ظ","unzo","ungzo",5);

    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
//
    }

    public Cursor allDataTahsin(){
        SQLiteDatabase db = this.getWritableDatabase();
        Cursor cursor = db.rawQuery("select * from tahsin", null);
        return cursor;
    }

    public Cursor allDataTajwid(){
        SQLiteDatabase db = this.getWritableDatabase();
        Cursor cursor = db.rawQuery("select * from tajwid", null);
        return cursor;
    }

    public Cursor allDataHukum(){
        SQLiteDatabase db = this.getWritableDatabase();
        Cursor cursor = db.rawQuery("select * from hukum", null);
        return cursor;
    }

}